### ISSUE TITLE
[Enchancement ] Code Hygiene

### ISSUE THREAD

**Issue by ternaus** [VoltaML/voltaML-fast-stable-diffusion#36]
The code is excellent from the scientific point of view, and I love how fast models work, but there is room for improvement in code hygiene.

It will significantly improve the code quality (easier to read, 10x faster to modify) if you add standard industry linters and formatters to the pre-commit and CI/CD.

* [pre-commit hook](https://pre-commit.com/)
* [black](https://github.com/psf/black)
* [ruff](https://github.com/charliermarsh/ruff)
* [mypy](https://mypy-lang.org/)
* [Sourcery](https://sourcery.ai/)

It will take only 20 minutes to add these checks to the code base, but the value they provide would be substantial.

**Comment by Stax124** [comment]
Hey, love to hear from another Pythonista.

I am already working on that - `experimental` branch is the one where the work can be seen. For now, there are no CI hooks because I am mostly working on that branch solo - for now - but I have some experience with it, so once I get some much needed time, these QOL improvements will come to CI.

(also love ruff but that linter is just not ready for production yet in my opinion, we are using pylint for now - slower but at least works predictably)

**Comment by ternaus** [comment]
I agree. Ruff is relatively new. The combination of isort, pylint, and flake8 is more mature and ready for production.

Subjectively, `mypy` will give the most immense value.

All my commits go through the pre-commit hook => CI/CD is secondary for solo work but crucial when several people are working on the project.

**Comment by Stax124** [comment]
I personally prefer using PyLance as it does not require me to "trace the library" and from my experience PyLint + PyLance gives an outstanding result when it comes to type safety and code quality that doesn't create 500+ errors because the underlying library did not follow the standard (as much as I love diffusers, they have really terrible type hints)

As `experimental` is mostly my doing when it comes to refactoring, I will stick to these software options for now, but if someone proves me wrong, I am willing to change it - It is a project for the community by the community after all.

**Comment by Stax124** [comment]
@ternaus Added pre-commit and CI for Black, I, unfortunately, cannot add any type checkers as the TRT code is full of errors due to PyTorch and TensorRT dependencies.

If you have any other recommendations, feel free to open a PR.

**Comment by ternaus** [comment]
> cannot add any type checkers as the TRT code is full of errors due to PyTorch and TensorRT dependencies.

This is exactly the point. Code is so entangled that it is non-trivial to do type checks => the mypy will give the largest value as it will enforce better quality code.

I think the best approach (I did it for my projects when integrated mypy) is to:
* Add `mypy` checks to pre-commit.
* Add `# type: ignore` to every problematic line.

=> you would be able to commit.

And add clear type hints to all later code. (You may revisit old one and clean it up, but it is optional)

**Comment by ternaus** [comment]
I use 

```
- name: Run pre-commit checks
        run: pre-commit run --all-files -a
```
in CI to make pre-commit and CI tests consistent.

**Comment by Stax124** [comment]
> I use
> 
> ```
> - name: Run pre-commit checks
>         run: pre-commit run --all-files -a
> ```
> 
> in CI to make pre-commit and CI tests consistent.

Can you point me to some repository that has this correctly implemented? I don't know where exactly I would put these lines.
It doesn't have proper syntax for .pre-commit-config.yaml, but the same applies to GitHub workflows.

**Comment by ternaus** [comment]
I have this file in all my python repos at `.github/workflows/ci.yml`

```
name: Python package

on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8" ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
      - name: Run pre-commit checks
        run: pre-commit run --all-files -a
      - name: Run tests
        run: pytest
```
